Update Messages.json
LeoSko/MindustryRankedStrings pull request #24
Opened 2022-02-07 12:26 UTC by Nunting

DONE.
More literal translation is needed, but it's not urgent right now. (Tired)

2022-02-07 12:38 UTC, LeoSko requested changes
That's a great contribution! Please take a bit more time on highlighted issues and I'll deploy within an hour.

2022-02-07 12:38 UTC, LeoSko commented on ko/Messages.json
> +    "SERVER_DESCRIPTION_2V2": "[#ff00ff]Season VII",
But it's season VIII already. :)

2022-02-07 12:38 UTC, LeoSko commented on ko/Messages.json
> +    "SERVER_DESCRIPTION_HEX": "[green]new quality level of hex\n[#ff00ff]Season VII",
Can you please translate this? Most probably this won't change.

2022-02-07 12:38 UTC, LeoSko commented on ko/Messages.json
> +    "RATING_CALCULATION_NEXT_TEAM_ELIMINATION_WARNING": "[red]Your rating change will be calculated when some next team will be eliminated",
Translate or exclude.

2022-02-07 12:38 UTC, LeoSko commented on ko/Messages.json
> +    "START_FORMAT": "[green]Map [yellow]@\n@\n@",
Translate or exclude.

2022-02-07 12:38 UTC, LeoSko commented on ko/Messages.json
> +    "START_FORMAT_UNRANKED": "[green]Map [yellow]@\nUnranked match\n@\n@",
Translate or exclude.

2022-02-07 12:38 UTC, LeoSko commented on ko/Messages.json
> +    "RATING_CHANGE": "Your rating: [orange]@->@[white] @",
Translate or exclude.

2022-02-07 12:38 UTC, LeoSko commented on ko/Messages.json
> +    "NOTHING_TO_WAIT": "[scarlet]Nothing to wait for",
Translate or exclude.

2022-02-07 12:38 UTC, LeoSko commented on ko/Messages.json
> +  "tutorial": {
Translate or exclude this whole section.

2022-02-07 12:38 UTC, LeoSko commented on ko/Messages.json
> +    "PLAYER_ABANDONED": "플레이어 @[white] from team [#@]@[]은 대결을 떠났고 다시는 돌아오지 않습니다."
Is "from team" translatable?

2022-02-07 12:38 UTC, LeoSko commented on ko/Messages.json
> +    "HISTORICAL_MATCH_ENTRY": "Match#@ @ [yellow]@\n[white]@\n@",
Translate or exclude.

2022-02-07 12:38 UTC, LeoSko commented on ko/Messages.json
> +    "BALANCE_BLOCKS": "[yellow]건설 블록[]\n20부터 시작해서, 건설 진행도에 비례해서 체력이 증가합니다   (기본 버전은 모든 과정에서 체력이 20).\n\n[yellow]보호막 프로젝터[]\n- 낙파 피해량을 33%까지 감소시키고, 보호막과 블록이 피해량을 나눠 받습니다\n- 건물에 피해를 입히는 대신 보호막이 덮인 건물 위
Here just a little thing left. :)

2022-02-07 12:38 UTC, LeoSko commented on ko/Messages.json
> +    "BALANCE_STATS": "[yellow]능력치[]\n체력 변경점은 데미지 배수를 설정된 데미지 배수를 거치고 적용됩니다.  (로직 역호환 가능)\n\n대거\uF800: 재장전 14⇨13\n메이스\uF7FF: [red]♥[]500⇨650, 30⇨34, 재장전 14⇨11, [yellow]\uE86B[]4⇨7\n포트리스\uF7FE: [red]♥
I'll accept `BALANCE_` translations for now, but keep in mind they change frequently. Next season I'll have to remove translation to make it actual.

2022-02-07 12:38 UTC, LeoSko commented on ko/Messages.json
> +    "CHAT_PREFIX_TEAM_ONLY_FORMAT": "([#@]@[]):",
Do not translate formats, which in fact don't have anything to translate.

2022-02-07 12:38 UTC, LeoSko commented on ko/Messages.json
> +    "SERVER_DESCRIPTION": "[red]매치메이킹 1 vs 1\n[#ff00ff]시즌 VIII",
Wrong color of the season. Use `[#87ceeb]`

2022-02-08 00:35 UTC, Nunting commented on ko/Messages.json
> +    "BALANCE_BLOCKS": "[yellow]건설 블록[]\n20부터 시작해서, 건설 진행도에 비례해서 체력이 증가합니다   (기본 버전은 모든 과정에서 체력이 20).\n\n[yellow]보호막 프로젝터[]\n- 낙파 피해량을 33%까지 감소시키고, 보호막과 블록이 피해량을 나눠 받습니다\n- 건물에 피해를 입히는 대신 보호막이 덮인 건물 위
I'm not sure what that part means

2022-02-08 04:32 UTC, closed without merging